spring.application.name=erp

spring.datasource.url=jdbc:mysql://localhost:3306/college_erp
spring.datasource.username=root
spring.datasource.password=suraj123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
